#! /bin/env bash

# SETTINGS
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g mouse on
set -g base-index 1
set -g detach-on-destroy on
set -g escape-time 0
set -g aggressive-resize on
set -g history-limit 1000000
set -g renumber-windows on
set -g set-clipboard on
set -g extended-keys on
set -g extended-keys-format csi-u
set-window-option -g mode-keys vi

# KEYBINDS
set -g prefix C-a
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R
bind | splitw -h
bind _ splitw -v
bind h previous-window
bind l next-window
bind-key -n M-s copy-mode
bind C-q kill-session
unbind q
bind q kill-window
unbind r
bind r source-file "$HOME/.config/tmux/tmux.conf"

unbind p
# shellcheck disable=SC2016
bind p if -F '#{==:#{session_name},floax-session}' 'detach-client' \
    'display-popup -w 90% -h 90%  -T "Floating Terminal" \
    -S fg=#5b8cf0 \
    -b heavy \
    -E \
    -d "#{pane_current_path}" \
    -e "FLOAX_PATH=#{pane_current_path}" \
    "$HOME/.config/tmux/scripts/floax-toggle"'

bind u display-popup -w 60% -h 50% -E "tv tmux-scrollback-patterns"

bind C-f display-popup -w 20% -h 30% -E "$HOME/.config/tmux/scripts/switch-session"

bind m display-popup -w 90% -h 90% -T "md_preview" -S fg=#8839EF -b heavy -E "$HOME/.config/tmux/scripts/md_preview"

bind e display-popup -w 90% -h 90% -T "Scrollback Edit" -S fg=#5b8cf0 -b heavy -E "$HOME/.config/tmux/scripts/vim_edit"

source-file ~/.config/tmux/status-bar.conf
