# see https://github.com/sigoden/aichat/blob/main/config.example.yaml
stream: false
save: true
messages_file: ~/messages.md
editor: nvim
theme: light
keybindings: vi
save_session: true
compress_threshold: 30000
summarize_prompt: "Summarize the discussion to use as a prompt for future context. include essential info that would be necessary for future follow ups"
summary_prompt: "This is a summary of the chat history as a recap: "
repl_prelude: role:caveman

document_loaders:
  pdf: "pdftotext $1 -"
function_calling: true # Enables or disables function calling (Globally).
mapping_tools: # Alias for a tool or toolset
  demo: "demo_py,get_current_weather"
use_tools: null # Which tools to use by default

model: deepseek
temperature: 0.5
top_p: 0.3
clients:
  - type: gemini
    api_key:
    patch:
      chat_completions:
        ".*":
          body:
            tools:
              - google_search: {}
  - type: openai-compatible
    name: deepseek
    api_base: https://api.deepseek.com
    api_key:
