#!/usr/bin/env bash
MSG_DIR="$HOME/.aichat/"
mkdir -p "$MSG_DIR"
file="$HOME/.aichat/$(basename "$(pwd)").md"
touch "$file"
echo >>"$file"
echo "---" >>"$file"
echo >>"$file"
wl-paste >>"$file"
tmp_file=$(mktemp --suffix=.md)
wl-paste >>"$tmp_file"
"$EDITOR" "$tmp_file"
rm -f "$tmp_file"
