hl.on("hyprland.start", function()
    local home_dir = os.getenv("HOME")
    hl.exec_cmd("sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("sunsetr")
    hl.exec_cmd("swaync")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hypridle")
    hl.exec_cmd(home_dir .. "/.config/scripts/blue_speaker")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("waybar")
    hl.exec_cmd("nm-applet --indicator")
end)

hl.on("config.reloaded", function()
    hl.exec_cmd("pkill waybar; waybar")
end)
