#!/usr/bin/env bash

sudo rm -rf /opt/T1000 && sudo rm -rf /opt/BotBrowser
[ ! -d /opt/T1000 ] && sudo mkdir /opt/T1000
sudo chmod -R 777 /opt/T1000
[ ! -d /opt/BotBrowser ] && sudo mkdir /opt/BotBrowser
sudo chmod -R 777 /opt/BotBrowser
[ ! -d /opt/T1000/fonts/ ] && sudo mkdir -p /opt/T1000/fonts/
sudo chmod -R 777 /opt/T1000/fonts

PROJECTS_DIR="$HOME/projects"
projects=(
    "dgscrp-dataimpact-scraping"
    "dgscrp-scraping-cli"
)
for PROJECT in "${projects[@]}"; do
    [ ! -d "$PROJECTS_DIR/$PROJECT" ] && git clone --depth 1 "git clone git@github.com-niq:niq-enterprise/$PROJECT.git" "$PROJECTS_DIR/$PROJECT"
done

env_files=(
    "dis.env"
    "discli.env"
)
DOTS_PATH="$HOME/dotfiles/secrets/"
for i in "${!env_files[@]}"; do
    PROJECT="${projects[$i]}"
    FILE="${env_files[$i]}"
    cp "$DOTS_PATH/$FILE" "$PROJECTS_DIR/$PROJECT/.env"
done

gum log -l info "work_setup done"
