return {
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    opts = {
      ensure_installed = {
        "lua_ls",
        "nixfmt",
        "statix",
        "asm_lsp",
        "asmfmt",
        "just-lsp",
        "jq-lsp",
        "ty",
        "gopls",
        "rust-analyzer",
        "iferr",
        "goimports",
        "gofumpt",
        "harper-ls",
        "prettypst",
        "tinymist",
        "clangd",
        "clang-format",
        "golines",
        "hyprls",
        "ruff",
        "systemdlint",
        "flake8",
        "mypy",
        "pyrefly",
        "zuban",
        "bash-language-server",
        "marksman",
        "markdownlint",
        "biome",
        "pyright",
        "basedpyright",
        "taplo",
        "dockerfile-language-server",
        "dockerfmt",
        "typescript-language-server",
        "tsgo",
        "prettierd",
        "css-lsp",
        "shellcheck",
        "fish-lsp",
        "shfmt",
        "stylua",
        "beautysh",
        "kdlfmt",
      },
    },
    dependencies = { { "mason-org/mason-lspconfig.nvim", opts = {} }, "neovim/nvim-lspconfig", "mason-org/mason.nvim" },
  },
  {
    "mason-org/mason.nvim",
    opts = {},
    keys = {
      {
        "<leader>mi",
        function()
          vim.cmd("Mason")
        end,
        mode = { "n", "v" },
        desc = "[M]ason [I]nfo",
      },
    },
  },
}
