#:schema https://mise.jdx.dev/schema/mise.json

[settings]
idiomatic_version_file_enable_tools = ['node', "python"]
trusted_config_paths = [
  "~/projects/dgscrp-dataimpact-scraping/",
  "~/projects/dgscrp-scraping-cli/",
  "~/projects/dotfiles/",
  "~/projects/neurogenesis/",
]
env_file = '.env'
activate_aggressive = true
lockfile = true

[tools]
usage = "latest"
