#:schema https://mise.jdx.dev/schema/mise.json

[settings]
idiomatic_version_file_enable_tools = ['node', "python"]
trusted_config_paths = [
  "~/dotfiles/",
  "~/projects/dgscrp-dataimpact-scraping/",
  "~/projects/dgscrp-scraping-cli/",
  "~/projects/neurogenesis/",
]
env_file = '.env'
activate_aggressive = true
lockfile = true

[tools]
usage = "3.5.3"
tmux = "3.6b"
deno = "2.9.0"
