#:schema https://mise.jdx.dev/schema/mise.json

[tasks.build]
run = "podman image build --build-arg PASS=0806 -t arch-test -f ./setup/Containerfile ."
[tasks.test]
depends = ["build"]
run = "podman container run -it --rm arch-test:latest"

[tasks.burn]
description = "Create bootable usb"
alias = "b"
usage = '''
arg "<iso>" help="ISO path"
'''

run = '''
caligula burn "$usage_iso" -f --root=always --interactive=never --hash=skip
'''

[shell_alias]
test_setup = "mise run test"
