#:schema https://mise.jdx.dev/schema/mise.json
[tasks.build]
usage = 'arg "<system>" help="Targeted System"'
run = 'podman image build --build-arg PASS=0806 -t "$usage_system"-test -f ./"$usage_system"/setup/Containerfile .'

[tasks.test]
usage = 'arg "<system>" help="Targeted System"'
depends = [{ task = "build", args = ["{{usage.system}}"] }]
run = 'podman container run -it --rm "$usage_system"-test:latest'

[tasks.burn]
description = "Create bootable usb"
alias = "b"
usage = '''
arg "<iso>" help="ISO path"
'''

run = '''
caligula burn "$usage_iso" -f --root=always --interactive=never --hash=skip
'''

[shell_alias]
test_arch = "mise run test arch"
