[bar.default]
thickness = 35
scale = 1.2
font_weight = 600
start = ["launcher", "wallpaper", "workspaces", "special-workspaces"]
center = ["clock"]
end = [
  "media",
  "tray",
  "notifications",
  "brightness",
  "battery",
  "session",
]
[widget.special-workspaces]
type = "jamesfeeder/special-workspaces:special-workspaces"
# hide_inactive = true
active_style = "fill"
# inactive_style = "ghost"
capsule_min_width = 80
# capsule_padding = 60
