[bar.default]
thickness = 35
scale = 1.2
font_weight = 600
start = ["launcher", "wallpaper", "workspaces", "special-workspaces"]
center = ["notifications", "clock", "caffeine"]
end = [
  "hypr-submap",
  "pomodoro-widget",
  "media",
  "tray",
  "brightness",
  "battery",
  "session",
]

[widget.clock]
capsule = true
capsule_fill = "primary"
capsule_opacity = 0.3
capsule_padding = 30
color = "primary"

[widget.clock.actions]
left = "panel-toggle control-center"

[widget.hypr-submap]
type = "k4n4t4/hypr-submap:hypr-submap"
prefix = " : "
capsule = true
capsule_border = "secondary"
capsule_fill = "tertiary"
capsule_opacity = 0.4
capsule_padding = 25
hide_when_default = true

[widget.special-workspaces]
type = "jamesfeeder/special-workspaces:special-workspaces"
active_style = "fill"
capsule_min_width = 80

[widget.pomodoro-widget]
type = "thepunkoff/pomodoro:widget"
capsule = true
capsule_opacity = 0.3
capsule_padding = 25
color = "tertiary"
icon_color = "primary"
capsule_border = "primary"
capsule_fill = "primary"
