#:schema https://mise.jdx.dev/schema/mise.json

[settings]
idiomatic_version_file_enable_tools = ['node', "python"]
trusted_config_paths = [
  "~/dotfiles/",
  "~/projects/dgscrp-dataimpact-scraping/",
  "~/projects/dgscrp-scraping-cli/",
  "~/projects/neurogenesis/",
]
env_file = '.env'
activate_aggressive = true
lockfile = true

[tools]
usage = "3.5.3"
pi = "0.80.3"
hunk = "0.16.0"
opencode = "1.18.3"

node = "26.4.0"
npm = "12.0.1"
deno = "2.9.3"
typst = "0.15.1"
uv = "0.11.29"
tree-sitter = "0.26.9"

direnv = "2.37.1"
fzf = "0.74.1"
starship = "1.26.0"
tmux = "3.7b"
zoxide = "0.10.0"
bat = "0.26.1"
bat-extras = "2024.08.24"
eza = "0.23.5"
fd = "10.4.2"
ripgrep = "15.2.0"
yazi = "26.5.6"
jq = "1.8.2"
jnv = "0.7.1"
jqp = "0.8.0"
miller = "6.20.2"
argc = "1.24.0"
bottom = "0.14.6"
fastfetch = "2.66.0"
glow = "2.1.2"
gum = "0.17.0"
hyperfine = "1.20.0"
just = "1.57.0"
television = "0.15.9"
