"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
palette = "catppuccin_mocha"
format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$lua\
$nodejs\
$golang\
$rust\
$package\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""
# move the rest of the prompt to the right
right_format = """$all"""
[fill]
symbol = ' '
[directory]
style = 'bold fg:lavender'
format = '[$path ]($style)'
truncation_length = 5
truncation_symbol = '…/'
truncate_to_repo = false
[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[git_branch]
style = 'fg:sapphire'
symbol = ' '
format = '[->](pink) [$symbol$branch ]($style)'

[git_status]
style = 'fg:red'
conflicted = '🏳'
ahead = '🏎💨'
behind = '😰'
diverged = '😵'
up_to_date = '✓'
# untracked = '🤷'
stashed = '📦'
modified = '📝[\($count\)](red)'
untracked = '🤷[\($count\)](red)'
format = '([$untracked$modified]())'

[python]
style = 'yellow bold'
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'


[lua]
symbol = ' '

[nodejs]
style = 'blue'
symbol = ' '
[golang]
style = 'blue'
symbol = ' '

[rust]
style = 'orange'
symbol = ' '

[ruby]
style = 'blue'
symbol = ' '

[package]
symbol = '󰏗 '

[docker_context]
symbol = ' '
style = 'fg:#06969A'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']
disabled = true

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style)'
[git_metrics]
[git_commit]
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
