hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("sunsetr")
    hl.exec_cmd("swaync")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("waybar")
    hl.exec_cmd("nm-applet --indicator")
end)

hl.on("config.reloaded", function()
    hl.exec_cmd("pkill waybar; waybar")
    hl.exec_cmd("pkill hyprpaper; hyprpaper")
    hl.exec_cmd("sleep 3; bluetoothctl connect 10:94:97:36:C7:15")
end)
