#:schema https://mise.jdx.dev/schema/mise.json
[tools]
python = "3.10"
uv = "0.11"


[tasks.deploy]
alias = "d"
run = '''
shub image upload "$SHUB_DEVZONE" --build-arg PYPI_SECRET="$PYPI_SECRET"
'''

[tasks.clone]
description = "Clone zyte job locally"
alias = "c"
usage = '''
arg "<job_url>" help="Zyte job url"
flag "-d --debug" help="Enable debugger"
'''
run = '''
tmp_file=$(mktemp --suffix=.sh)
cmd=$(pls job clone --local "$usage_job_url")
if [ -n "$usage_debug" ]; then
    echo "$cmd --pdb" >&2 >"$tmp_file"
else
    echo "$cmd" >&2 >"$tmp_file"
fi
sh "$tmp_file"

'''
[tasks.uv_install]
description = "install project dependencies"
alias = "i"
run = '''
uv pip install --extra-index-url "https://_json_key_base64:${PYPI_SECRET}@europe-python.pkg.dev/infra-prod-49751107/di-pypi/simple" -r requirements.txt  -r requirements-dev.txt
uv pip uninstall bezier && BEZIER_NO_EXTENSION=true uv pip install --upgrade bezier --no-binary=bezier && uv pip install numpy==1.26.4
uv pip install shub

'''
[hooks.enter]
shell = "zsh"
script = """
#!/usr/bin/env zsh
shub_deploy_shortcut() {
    shub image upload "$SHUB_DEVZONE" --build-arg PYPI_SECRET="$PYPI_SECRET"
    shub_deploy
    zle redisplay
}
zle -N shub_deploy_shortcut
bindkey '^x^u' shub_deploy_shortcut

"""
[hooks.leave]
shell = "zsh"
script = """
#!/usr/bin/env zsh
unfunction shub_deploy_shortcut
zle -D shub_deploy_shortcut
bindkey -r '^x^u'
"""

[env]
PROJECT_NAME = "{{ config_root | basename }}"
_.file = ".env"
_.python.venv = { path = ".venv", create = true }

[settings]
lockfile = true
