alias gclean="git clean -f"
alias lc="leetcode"
alias e='$EDITOR'
alias nv="nvim"
alias nvconfig="cd ~/.config/nvim && nv"
alias tmuxconf="nv ~/.tmux.conf"
alias t="tmuxp load -y"
alias c="clear"
alias ..="cd .."
alias mkdir="mkdir -pv"
alias grep="grep --color=auto"
alias xcurl="curl -x 127.0.0.1:8000 -k "
alias zshconfig="cd ~/zsh && nv"
alias zbench="hyperfine --warmup 5 'zsh -i -c exit'"
alias xel="fc"
alias dotconf="cd ~/.config"
alias nvim_shada_clear="rm ~/.local/state/nvim/shada/main.shada"
alias hd="hunk diff"
