#!/usr/bin/env zsh

source "$HOME/.config/zinit/zinit.sh"

bindkey -e
bindkey '^y' autosuggest-accept
bindkey '^ ' autosuggest-execute
bindkey '^o' forward-word
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
autoload edit-command-line
zle -N edit-command-line
bindkey "^E" edit-command-line
autoload -Uz select-word-style
select-word-style bash

export HISTDUP=erase

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' menu select

_evalcache mise activate zsh
if [[ ! -f "$HOME/.zfunc/_mise" ]]; then
    mise completion zsh >"$HOME/.zfunc/_mise"
fi
_evalcache tv init zsh
_evalcache batman --export-env

export AICHAT_MESSAGES_FILE="$HOME/messages.md"
aises() { aichat -s "$(basename "$(pwd)")"; }
aichat_hist() { nvim "$HOME/.aichat/$(basename "$(pwd)").md"; }

if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR="vim"
fi

zinit cdreplay -q
