#!/usr/bin/env bash
set -euo pipefail

options="Open Notifications Center\nClear All Notifications"
selection=$(echo -e "$options" | fuzzel --dmenu --prompt="Notifications Center ❯ " --lines=2 --width=35)

case "$selection" in
    *"Open"*) swaync-client -t ;;
    *"Clear"*) swaync-client -C ;;
esac
