#!/usr/bin/env zsh

# TODO: zsh lsp-config : shuck / zshcs
# optimize startup time
# nix rebuild keybind
source "$HOME/.config/zinit/zinit.sh"

_evalcache fzf --zsh
_evalcache direnv hook zsh
_evalcache starship init zsh
_evalcache tv init zsh
_evalcache zoxide init zsh
_evalcache batman --export-env

bindkey '^y' autosuggest-accept
bindkey '^ ' autosuggest-execute
bindkey '^o' forward-word
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
autoload edit-command-line
zle -N edit-command-line
bindkey "^E" edit-command-line
autoload -Uz select-word-style
select-word-style bash


if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR="vim"
fi
zinit cdreplay -q
