[code]
editor = "nvim"
lang = "python3"
start_marker = "##################################################################################"
end_marker = "##################################################################################"
comment_problem_desc = true
comment_leading = "#"
inject_before = ["from typing import List \n"]

[cookies]
csrf = ""
session = ""
site = "leetcode.com"

[storage]
cache = "problems-cache"
code = "problems/python"
root = "~/neurogenesis"
scripts = "scripts"
