FROM archlinux:base-devel
LABEL maintainer="hh9dj <https://github.com/hh9dj>"

ARG BRANCH=master
ARG USER=test-user

RUN pacman -Syyu --noconfirm go vim gum git go-yq

COPY arch/packages.yml /tmp/
RUN yq -r '.pacman.base // [] | .[] | select(. != null)' /tmp/packages.yml >/tmp/pacman-base.txt \
    && if [ -s /tmp/pacman-base.txt ]; then pacman -Sq --noconfirm --noprogressbar --needed --disable-download-timeout - </tmp/pacman-base.txt; fi

RUN useradd --system --create-home ${USER} \
    && echo "${USER} ALL=(ALL:ALL) NOPASSWD:ALL" >/etc/sudoers.d/${USER}

USER ${USER}
WORKDIR /home/${USER}

RUN git clone https://aur.archlinux.org/yay.git /tmp/yay \
    && cd /tmp/yay \
    && makepkg -sri --needed --noconfirm \
    && rm -rf /tmp/yay /home/${USER}/.cache

RUN yq -r '.aur.base // [] | .[] | select(. != null)' /tmp/packages.yml >/tmp/aur-base.txt \
    && if [ -s /tmp/aur-base.txt ]; then script -q -c "yay -S --noconfirm --needed --disable-download-timeout - < /tmp/aur-base.txt" /dev/null; fi

USER root
COPY . /home/${USER}/dotfiles
RUN chown -R ${USER}:${USER} /home/${USER}/dotfiles

USER ${USER}

ENV USER=${USER}
ENV TERM=xterm-256color
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8

CMD ["bash", "-c", "bash /home/test-user/dotfiles/arch/init.sh ${BRANCH} ; exec bash"]
