[metadata]
name = "tmux-scrollback-patterns"
description = "Pick entries from the current tmux window scrollback"
requirements = ["tmux", "xre", "wl-copy"]

[source]
[[source.command]]
name = "URLs"
run = '''o=$(tmux capture-pane -J -p -S -2000 | xre \
        -e '(https?|ftp|file):/?//[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]' \
        -e 'git@([^:]+):(.+)\.git' -r 'https://$1/$2' \
        -e '(www\.\S+)' -r 'http://$1' \
        -e '(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}(?::\d{1,5})?(?:/[^\s]+)*)' -r 'http://$1'); \
        printf '%s\n' "$o"'''

[[source.command]]
name = "File Paths"
run = '''o=$(tmux capture-pane -J -p -S -2000 | xre -e '(?:~/|\.\.?/|/)[\w./~-]+'); printf '%s\n' "$o"'''

[ui.preview_panel]
hidden = true

[keybindings]
enter = ["copy_entry_to_clipboard", "quit"]
ctrl-o = "actions:open"


[actions.open]
description = "Open with default browser"
command = "xdg-open {} 2>/dev/null || open {}"
mode = "fork"
