#!/usr/bin/env bash

sudo rm -rf /opt/T1000 && sudo rm -rf /opt/BotBrowser
[ ! -d /opt/T1000 ] && sudo mkdir /opt/T1000
sudo chmod -R 777 /opt/T1000
[ ! -d /opt/BotBrowser ] && sudo mkdir /opt/BotBrowser
sudo chmod -R 777 /opt/BotBrowser
[ ! -d /opt/T1000/fonts/ ] && sudo mkdir -p /opt/T1000/fonts/
sudo chmod -R 777 /opt/T1000/fonts

ssh_private_key="$HOME/.ssh/work_github"
eval "$(ssh-agent -s)"
chmod 600 "$ssh_private_key"
ssh-add "$ssh_private_key"

PROJECTS_DIR="$HOME/projects"

declare -A project_envs=(
    ["dgscrp-dataimpact-scraping"]="dis.env"
    ["dgscrp-scraping-cli"]="discli.env"
)

for PROJECT in "${!project_envs[@]}"; do
    [ ! -d "$PROJECTS_DIR/$PROJECT" ] && git clone "git@github.com-niq:niq-enterprise/$PROJECT.git" "$PROJECTS_DIR/$PROJECT"
done

DOTS_PATH="$HOME/dotfiles/arch/secrets/"
for PROJECT in "${!project_envs[@]}"; do
    FILE="${project_envs[$PROJECT]}"
    cp "$DOTS_PATH/$FILE" "$PROJECTS_DIR/$PROJECT/.env"
done

gum log -l info "work_setup done"
