#! /bin/env bash
set -g prefix C-a

bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R
bind | splitw -h
bind _ splitw -v
bind h previous-window
bind l next-window
bind-key -n M-s copy-mode
bind C-q kill-session
unbind q
bind q kill-window