#! /bin/env bash
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'fcsonline/tmux-thumbs'
run-shell "$HOME/.tmux/plugins/tmux-thumbs/tmux-thumbs.tmux"
set -g @thumbs-command ' wl-copy {} '
#################################################
