#! /bin/env bash
####### STATUS BAR SETTINGS #######
####### VARIABLES (Colors) #######
set -g @text_color "#000000"       
set -g @inactive_color "#cdd6f4"    
set -g @active_color "#a6adc8"    
set -g @session_color "#89b4fa"  
set -g @prefix_color "#f38ba8"
set -g @left_bubble_color "#a6e3a1" 
set -g status-position top
set -g status-justify "absolute-centre"
set -g status 2
set -g status-style "bg=default,fg=default"
set -g status-format[1] " "
set -g window-status-style "bg=default,fg=default"
set -g window-status-current-style "bg=default,fg=default"
####### INACTIVE WINDOWS #######
set -g window-status-format "\
#[fg=#{@inactive_color},bg=default]\
#[fg=#{@text_color},bg=#{@inactive_color}] #W \
#[fg=#{@inactive_color},bg=default]"
####### ACTIVE WINDOW #######
set -g window-status-current-format "\
#[fg=#{@active_color},bg=default]\
#[fg=#{@text_color},bg=#{@active_color},bold] #W \
#[fg=#{@active_color},bg=default]"
####### SESSION BUBBLE (RIGHT SIDE) #######
# Changes color dynamically when prefix key is pressed
set -g status-right "\
#[fg=#{?client_prefix,#{@prefix_color},#{@session_color}},bg=default]\
#[fg=#{@text_color},bg=#{?client_prefix,#{@prefix_color},#{@session_color}}]  #S \
#[fg=#{?client_prefix,#{@prefix_color},#{@session_color}},bg=default]  "
set -g status-left "\
#[fg=#{@left_bubble_color},bg=default]\
#[fg=#{@text_color},bg=#{@left_bubble_color}] 󰓩 #(tmux list-sessions | wc -l | tr -d '[:space:]') \
#[fg=#{@left_bubble_color},bg=default]"
