#!/usr/bin/env zsh

# TODO: zsh lsp-config : shuck / zshcs

eval "$(batman --export-env)"

bindkey '^y' autosuggest-accept
bindkey '^ ' autosuggest-execute
bindkey '^o' forward-word
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
bindkey "^[c" undefined-key
autoload edit-command-line
zle -N edit-command-line
bindkey "^E" edit-command-line
autoload -Uz select-word-style
select-word-style bash


if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR="vim"
fi
