#! /bin/env bash

source-file "$HOME/.config/tmux/core.conf"
source-file "$HOME/.config/tmux/keybindings.conf"
source-file "$HOME/.config/tmux/plugins.conf"
source-file "$HOME/.config/tmux/floax.conf"
source-file "$HOME/.config/tmux/fzf-sessions.conf"
source-file "$HOME/.config/tmux/status.conf"
source-file "$HOME/.config/tmux/md_preview.conf"
source-file "$HOME/.config/tmux/vim_edit.conf"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "$HOME/.tmux/plugins/tpm/tpm"
