#! /bin/env bash

bind p \
    if -F '#{==:#{session_name},floax-session}' \
        'detach-client' \
        'display-popup \
            -w 90% -h 90% \
            -T "Floating Terminal" \
            -S fg=#5b8cf0 \
            -b heavy \
            -E \
            -d "#{pane_current_path}" \
            -e "FLOAX_PATH=#{pane_current_path}" \
            "$HOME/.config/tmux/scripts/floax-toggle"'
