#! /bin/env bash
# Unbind default C-b conflicting prefix
unbind-key C-b
# Sending prefix to shell (C-a C-a)
bind-key C-a send-prefix
# Quick last-window via prefix char (C-a a)
bind-key a last-window
# Reload tmux config (prefix R)
bind r run "tmux source-file ~/.config/tmux/tmux.conf"

bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R
bind | splitw -h
bind _ splitw -v
bind h previous-window
bind l next-window
unbind p
bind-key -n M-s copy-mode
bind C-q kill-session
unbind q
bind q kill-window
