FROM archlinux:latest
LABEL maintainer="H-ADJI <https://github.com/H-ADJI>"
ENV TERM=xterm-256color
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8
RUN pacman -Syu --noconfirm curl
ARG USER=test-user
ARG PASS
RUN useradd -m ${USER} &&  echo "${USER}:${PASS}" | chpasswd 
RUN echo "${USER} ALL=(ALL) ALL" >> /etc/sudoers
USER ${USER}
WORKDIR /home/${USER}
# TODO: take branch name as arg for easy testing
CMD ["/bin/bash","-c","curl -fsSL https://raw.githubusercontent.com/H-ADJI/dotfiles/migration/multi_os_setup/init.sh | bash ; exec bash"]
