FROM archlinux:latest
LABEL maintainer="H-ADJI <https://github.com/H-ADJI>"
ENV TERM=xterm-256color
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8
RUN pacman -Syu --noconfirm \
  && pacman -S --noconfirm curl base-devel
ARG USER=test-user
ARG PASS
RUN useradd -m ${USER} &&  echo "${USER}:${PASS}" | chpasswd 
RUN echo "${USER} ALL=(ALL) ALL" >> /etc/sudoers
USER ${USER}
WORKDIR /home/${USER}
CMD ["/bin/bash","-c","curl -fsSL conf.hadji.org/setup | bash ; exec bash"]
