#!/bin/bash

COMPOSITOR=$(gum choose hypr sway)
_checkCommandExists() {
    package="$1"
    if ! command -v "$package" >/dev/null; then
        return 1
    else
        return 0
    fi
}
_installYay() {
    [ ! -d "yay" ] && git clone --depth 1 https://aur.archlinux.org/yay.git
    cd "yay" || return 1
    makepkg -si --noconfirm
    cd || return 1
}
install_AUR_helper() {
    cd || exit 1
    if _checkCommandExists "yay"; then
        gum log -l info ":: yay is already installed"
    else
        gum log -l info ":: The installer requires yay. yay will be installed now"
        _installYay
    fi
}
installpackages() {
    gum log -l info "[START] Installing $COMPOSITOR packages"
    yay -Sq --noconfirm --noprogressbar --needed --disable-download-timeout - \
        <~/dotfiles/setup/"$COMPOSITOR"/requirements.txt
    gum log -l info "[DONE] Installing $COMPOSITOR packages"

    gum log -l info "[START] Installing common packages"
    yay -Sq --noconfirm --noprogressbar --needed --disable-download-timeout - \
        <~/dotfiles/setup/requirements.txt
    gum log -l info "[DONE] Installing common packages"

}

personal_repos() {
    projects_dir="$HOME/projects"
    mkdir "$projects_dir"
    projects=(
        "ccraft"
        "homelab"
        "neurogenesis"
        "secondBrain"
        "zmk-config"
        "learn_nix"
    )
    for project in "${projects[@]}"; do
        [ ! -d "$project" ] && git clone --depth 1 "git@github.com:H-ADJI/$project.git" "$projects_dir/$project"
    done
    cd ~/dotfiles/ || return 1
    git remote remove origin
    git remote add origin git@github.com:H-ADJI/dotfiles.git
    cd || exit 1
}

setup() {

    gum log -l info "[START] transcrypt decryption"
    decrypt_secrets
    gum log -l info "[DONE] transcrypt decryption"

    gum log -l info "[START] Remove default compositor config"
    rm -rf "$HOME/.config/$COMPOSITOR"
    gum log -l info "[DONE] Remove default compositor config"

    gum log -l info "[START] Linking dots"
    link_dotfiles
    gum log -l info "[DONE] Linking dots"

    gum log -l info "[START] ssh setup"
    ssh_setup
    gum log -l info "[DONE] ssh setup"

    gum log -l info "[START] docker post install steps"
    sudo usermod -aG docker "$USER"
    gum log -l info "[DONE] docker post install steps"

    gum log -l info "[START] Clone some repos"
    personal_repos
    gum log -l info "[DONE] Clone some repos"

    gum log -l info "[START] nvim headless install"
    nvim --headless -c 'Lazy install' -c 'MasonToolsInstallSync' -c 'qa'
    gum log -l info "[DONE] nvim headless install"

    gum log -l info "[START] Set timezone"
    sudo timedatectl set-timezone Europe/Paris
    gum log -l info "[DONE] Set timezone"

    gum log -l info "[START] Enable iwd service"
    sudo systemctl enable --now iwd.service
    gum log -l info "[DONE] Enable iwd service"

    gum log -l info "[START] Enable docker service"
    sudo systemctl enable docker.service
    gum log -l info "[DONE] Enable docker service"

    gum log -l info "[START] Enable NetworkManager service"
    sudo systemctl enable NetworkManager.service
    gum log -l info "[DONE] Enable NetworkManager service"

    gum log -l info "[START] Enable bluetooth service"
    sudo systemctl enable bluetooth.service
    gum log -l info "[DONE] Enable bluetooth service"

    gum log -l info "[START] Enable polikit service"
    systemctl --user enable --now hyprpolkitagent
    gum log -l info "[DONE] Enable polikit service"

    gum log -l info "[START] copy ZSH history"
    cp ~/dotfiles/zsh/dot-zsh_history ~/.zsh_history
    gum log -l info "[DONE] copy ZSH history"

    gum log -l info "[START] Installing mise tools"
    mise i --locked
    gum log -l info "[DONE] Installing mise tools"

    gum log -l info "[START] Installing TPM"
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    gum log -l info "[DONE] Installing TPM"

    gum log -l info "[START] Install tmux plugins"
    sh ~/.tmux/plugins/tpm/bin/install_plugins
    gum log -l info "[DONE] Install tmux plugins"

    gum log -l info "[START] Default shelll"
    which zsh | sudo tee -a /etc/shells
    gum log -l info "[DONE] Default shell"

    gum log -l info "[START] Default apps"
    xdg-mime default imv.desktop image/jpeg
    xdg-mime default imv.desktop image/png
    xdg-mime default google-chrome.desktop application/pdf
    xdg-mime default google-chrome.desktop x-scheme-handler/https
    xdg-mime default google-chrome.desktop x-scheme-handler/http
    xdg-mime default google-chrome.desktop application/html
    xdg-mime default google-chrome.desktop application/octet-stream
    gum log -l info "[DONE] Default apps"

}

decrypt_secrets() {
    cd ~/dotfiles/ || return 1
    VERIFY=1
    STORED_HASH=$(cat setup/lock.secure)
    while true; do
        MASTER_PASSWORD=$(
            gum input --prompt "Master Password> " --password
        )
        COMPUTED_HASH=$(echo -n "$MASTER_PASSWORD" | argon2 "08061999" -r)
        if [ "$VERIFY" -eq 0 ]; then
            break
        fi
        if [ "$COMPUTED_HASH" = "$STORED_HASH" ]; then
            gum log -l info "✅ Correct password"
            break
        else
            gum log -l error "❌ Wrong password, try again"
        fi
    done
    transcrypt -y -p "$MASTER_PASSWORD"
    cd || return 1
}
link_dotfiles() {
    dotfiles=(
        "aichat"
        "alacritty"
        "assets"
        "bat"
        "browser"
        "fastfetch"
        "fuzzel"
        "git"
        "hunk"
        "jnv"
        "jqp"
        "leetcode"
        "mise"
        "nvim"
        "pipewire"
        "pulsemixer"
        "ruff"
        "scripts"
        "ssh"
        "starship"
        "sunsetr"
        "swappy"
        "tabiew"
        "task"
        "tmux"
        "tv"
        "walt"
        "wezterm"
        "yazi"
        "zsh"
        "$COMPOSITOR"
    )
    stow --dotfiles --adopt -d "$HOME/dotfiles/" -t "$HOME" "${dotfiles[@]}"
}
ssh_setup() {
    local ssh_private_key="$HOME/.ssh/ssh_git"
    eval "$(ssh-agent -s)"
    chmod 600 "$ssh_private_key"
    ssh-add "$ssh_private_key"

}

install_AUR_helper
installpackages
setup
