zinit light "zsh-users/zsh-syntax-highlighting"
zinit light "zsh-users/zsh-autosuggestions"
zinit light "zsh-users/zsh-completions"
zinit light "mroth/evalcache"
zinit light "Aloxaf/fzf-tab"
zinit light "Aloxaf/fzf-tab"
