alias now="date +'%Y-%m-%d %H:%M:%S'"
alias csv_to_json="jq -Rsn '(input | split(\"\n\") | .[1:] | map(select(length > 0) | split(\",\") | {url: .[0], path: .[1], params: null}))' > paths.json"
alias spotdl="docker run --rm -v ~/Music:/music spotdl/spotify-downloader download"
alias c="clear"
alias q="exit"
alias ..="cd .."
alias mkdir="mkdir -pv"
alias grep="grep --color=auto"
alias envrc="cp ~/dotfiles/direnv/.envrc.sample ."
alias copy="wl-copy"
alias pst="wl-paste"
# alias brave="brave --password-store=basic"
alias unlock_transcrypt="transcrypt -y -p "
