alias now="date +'%Y-%m-%d %H:%M:%S'"
alias csv_to_json="jq -Rsn '(input | split(\"\n\") | .[1:] | map(select(length > 0) | split(\",\") | {url: .[0], path: .[1], params: null}))' > paths.json"
alias spotdl="docker run --rm -v ~/Music:/music spotdl/spotify-downloader download"
alias c="clear"
alias q="exit"
alias ..="cd .."
alias mkdir="mkdir -pv"
alias grep="grep --color=auto"
alias copy="wl-copy"
alias pst="wl-paste"
# alias brave="brave --password-store=basic"
alias unlock_transcrypt="transcrypt -y -p "
alias envrc="cp ~/dotfiles/direnv/.envrc.sample .envrc"
alias bezier_python_bininstall="uv pip uninstall bezier && BEZIER_NO_EXTENSION=true uv pip install --upgrade bezier --no-binary=bezier numpy==1.26.4"
