alias tmuxconf="nv ~/.tmux.conf"
alias tn="tmux new -s"
alias install_tpm_plugins="~/.tmux/plugins/tpm/bin/install_plugins"
alias dots="tmuxp load -y dots"
alias cli="tmuxp load -y scraping_cli"
alias crapy="tmuxp load -y scraping"
alias notes="tmuxp load -y notes"
alias homelab="tmuxp load -y homelab"
